#!/bin/bash
#SBATCH --job-name="skirt_images_all"
#SBATCH --output="skirt_images_all.%j.%N.out"
#SBATCH --partition=compute
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --export=ALL
#SBATCH -t 48:00:00
#SBATCH --mail-type=END,FAIL
#SBATCH --mail-user=daniellerenniks@gmail.com

cd $SLURM_SUBMIT_DIR

#sbatch skirt_images_0.sh
sbatch skirt_images_1.sh
sbatch skirt_images_2.sh
sbatch skirt_images_3.sh
sbatch skirt_images_4.sh
sbatch skirt_images_5.sh
sbatch skirt_images_6.sh
sbatch skirt_images_7.sh
sbatch skirt_images_8.sh
sbatch skirt_images_9.sh
sbatch skirt_images_10.sh
sbatch skirt_images_11.sh
sbatch skirt_images_12.sh
sbatch skirt_images_13.sh
sbatch skirt_images_14.sh
sbatch skirt_images_15.sh
sbatch skirt_images_16.sh
sbatch skirt_images_17.sh
sbatch skirt_images_18.sh
sbatch skirt_images_19.sh
sbatch skirt_images_20.sh
sbatch skirt_images_21.sh
sbatch skirt_images_22.sh
sbatch skirt_images_23.sh
sbatch skirt_images_24.sh
sbatch skirt_images_25.sh
sbatch skirt_images_26.sh
sbatch skirt_images_27.sh
sbatch skirt_images_28.sh
sbatch skirt_images_29.sh
sbatch skirt_images_30.sh
sbatch skirt_images_31.sh
sbatch skirt_images_32.sh
sbatch skirt_images_33.sh
sbatch skirt_images_34.sh
sbatch skirt_images_35.sh
sbatch skirt_images_36.sh
sbatch skirt_images_37.sh
sbatch skirt_images_38.sh
sbatch skirt_images_39.sh
sbatch skirt_images_40.sh
sbatch skirt_images_41.sh
sbatch skirt_images_42.sh
sbatch skirt_images_43.sh
sbatch skirt_images_44.sh
sbatch skirt_images_45.sh
sbatch skirt_images_46.sh
sbatch skirt_images_47.sh
sbatch skirt_images_48.sh
sbatch skirt_images_49.sh
sbatch skirt_images_50.sh
sbatch skirt_images_51.sh
sbatch skirt_images_52.sh
sbatch skirt_images_53.sh
sbatch skirt_images_54.sh
sbatch skirt_images_55.sh
sbatch skirt_images_56.sh
sbatch skirt_images_57.sh
sbatch skirt_images_58.sh
sbatch skirt_images_59.sh
sbatch skirt_images_60.sh
sbatch skirt_images_61.sh
sbatch skirt_images_62.sh
sbatch skirt_images_63.sh
sbatch skirt_images_64.sh
sbatch skirt_images_65.sh
sbatch skirt_images_66.sh
sbatch skirt_images_67.sh
sbatch skirt_images_68.sh
sbatch skirt_images_69.sh
sbatch skirt_images_70.sh
sbatch skirt_images_71.sh
sbatch skirt_images_72.sh
sbatch skirt_images_73.sh
sbatch skirt_images_74.sh
sbatch skirt_images_75.sh
sbatch skirt_images_77.sh
sbatch skirt_images_78.sh
sbatch skirt_images_80.sh
sbatch skirt_images_81.sh
sbatch skirt_images_82.sh
sbatch skirt_images_83.sh
sbatch skirt_images_84.sh
sbatch skirt_images_85.sh
sbatch skirt_images_86.sh
sbatch skirt_images_87.sh
sbatch skirt_images_88.sh
sbatch skirt_images_90.sh
sbatch skirt_images_92.sh
sbatch skirt_images_93.sh
sbatch skirt_images_94.sh
sbatch skirt_images_95.sh
sbatch skirt_images_96.sh
sbatch skirt_images_97.sh
sbatch skirt_images_98.sh
sbatch skirt_images_99.sh
sbatch skirt_images_100.sh
sbatch skirt_images_101.sh
sbatch skirt_images_102.sh
sbatch skirt_images_103.sh
sbatch skirt_images_104.sh
sbatch skirt_images_105.sh
sbatch skirt_images_106.sh
sbatch skirt_images_107.sh
sbatch skirt_images_108.sh
sbatch skirt_images_109.sh
sbatch skirt_images_110.sh
sbatch skirt_images_111.sh
sbatch skirt_images_112.sh
sbatch skirt_images_113.sh
sbatch skirt_images_115.sh
sbatch skirt_images_116.sh
sbatch skirt_images_117.sh
sbatch skirt_images_118.sh
sbatch skirt_images_119.sh
sbatch skirt_images_120.sh
sbatch skirt_images_121.sh
sbatch skirt_images_122.sh
sbatch skirt_images_123.sh
sbatch skirt_images_124.sh
sbatch skirt_images_125.sh
sbatch skirt_images_126.sh
sbatch skirt_images_127.sh
sbatch skirt_images_128.sh
sbatch skirt_images_129.sh
sbatch skirt_images_130.sh
sbatch skirt_images_131.sh
sbatch skirt_images_132.sh
sbatch skirt_images_133.sh
sbatch skirt_images_135.sh
sbatch skirt_images_136.sh
sbatch skirt_images_137.sh
sbatch skirt_images_138.sh
sbatch skirt_images_139.sh
sbatch skirt_images_140.sh
sbatch skirt_images_141.sh
sbatch skirt_images_142.sh
sbatch skirt_images_143.sh
sbatch skirt_images_144.sh
sbatch skirt_images_145.sh
sbatch skirt_images_146.sh
sbatch skirt_images_147.sh
sbatch skirt_images_148.sh
sbatch skirt_images_149.sh
sbatch skirt_images_150.sh
sbatch skirt_images_151.sh
sbatch skirt_images_152.sh
sbatch skirt_images_153.sh
sbatch skirt_images_154.sh
sbatch skirt_images_155.sh
sbatch skirt_images_156.sh
sbatch skirt_images_157.sh
sbatch skirt_images_158.sh
sbatch skirt_images_159.sh
sbatch skirt_images_160.sh
sbatch skirt_images_161.sh
sbatch skirt_images_162.sh
sbatch skirt_images_163.sh
sbatch skirt_images_164.sh
sbatch skirt_images_165.sh
sbatch skirt_images_166.sh
sbatch skirt_images_167.sh
sbatch skirt_images_168.sh
sbatch skirt_images_169.sh
sbatch skirt_images_172.sh
sbatch skirt_images_173.sh
sbatch skirt_images_174.sh
sbatch skirt_images_175.sh
sbatch skirt_images_176.sh
sbatch skirt_images_178.sh
sbatch skirt_images_181.sh
sbatch skirt_images_183.sh
sbatch skirt_images_184.sh
sbatch skirt_images_185.sh
sbatch skirt_images_186.sh
sbatch skirt_images_187.sh
sbatch skirt_images_188.sh
sbatch skirt_images_189.sh
sbatch skirt_images_190.sh
sbatch skirt_images_192.sh
sbatch skirt_images_193.sh
sbatch skirt_images_194.sh
sbatch skirt_images_195.sh
sbatch skirt_images_196.sh
sbatch skirt_images_197.sh
sbatch skirt_images_199.sh
sbatch skirt_images_200.sh
sbatch skirt_images_201.sh
sbatch skirt_images_202.sh
sbatch skirt_images_203.sh
sbatch skirt_images_204.sh
sbatch skirt_images_205.sh
sbatch skirt_images_206.sh
sbatch skirt_images_208.sh
sbatch skirt_images_209.sh
sbatch skirt_images_210.sh
sbatch skirt_images_211.sh
sbatch skirt_images_212.sh
sbatch skirt_images_214.sh
sbatch skirt_images_215.sh
sbatch skirt_images_216.sh
sbatch skirt_images_218.sh
sbatch skirt_images_219.sh
sbatch skirt_images_220.sh
sbatch skirt_images_223.sh
sbatch skirt_images_226.sh
sbatch skirt_images_228.sh
sbatch skirt_images_229.sh
sbatch skirt_images_230.sh
sbatch skirt_images_231.sh
sbatch skirt_images_232.sh
sbatch skirt_images_235.sh
sbatch skirt_images_238.sh
sbatch skirt_images_243.sh
sbatch skirt_images_244.sh
sbatch skirt_images_245.sh
sbatch skirt_images_247.sh
sbatch skirt_images_249.sh
sbatch skirt_images_252.sh
sbatch skirt_images_254.sh
sbatch skirt_images_255.sh
sbatch skirt_images_259.sh
sbatch skirt_images_261.sh
sbatch skirt_images_277.sh
sbatch skirt_images_281.sh
sbatch skirt_images_314.sh
